[project]
name = "absurdbot"
version = "0.2.0"
description = "A bot."
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "discord-py>=2.6.4",
    "fastapi[standard]>=0.121.0",
    "ffmpeg-python>=0.2.0",
    "filetype>=1.2.0",
    "glitch-this>=1.0.3",
    "numpy>=2.3.4",
    "pedalboard",
    "pillow>=12.0.0",
    "pydub>=0.25.1",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
    "wand>=0.6.13",
]

[tool.uv]
required-environments = [
    "sys_platform == 'manylinux2_28' and platform_machine == 'x86_64'",
]