import random
import traceback

import discord
import requests
from discord.ext import commands
from random import randint

class InternetCommands(commands.Cog, name="Internet"):
    def __init__(self):
        pass

    @commands.command(brief="AI-generated inspirational quotes.")
    async def inspirobot(self, ctx):
        """Get an inspirational quote from the InspiroBot.me website."""
        try:
            link = requests.get("https://inspirobot.me/api?generate=true").content.decode(encoding="utf-8")
            embed = discord.Embed(
                title="InspiroBot",
                color=discord.Color.random()
            )
            embed.set_image(url=link)
            embed.set_footer(text="Generated by InspiroBot.me")
            await ctx.send(embed=embed)
        except ConnectionError:
            print(traceback.format_exc())
            embed = discord.Embed(
                title="InspiroBot",
                description="Failed to get post from InspiroBot api. Is the site down?",
                color=discord.Color.red()
            )
            await ctx.send(embed=embed)
